---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-spec-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-spec-sync
  template:
    metadata:
      labels:
        name: governance-policy-spec-sync
    spec:
      serviceAccountName: governance-policy-spec-sync
      containers:
        - name: governance-policy-spec-sync
          image: quay.io/stolostron/governance-policy-spec-sync:latest-dev
          command:
          - governance-policy-spec-sync
          args:
            - '--hub-cluster-configfile=/var/run/klusterlet/kubeconfig'
          imagePullPolicy: Always
          volumeMounts:
            - name: klusterlet-config
              mountPath: /var/run/klusterlet
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-spec-sync"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            failureThreshold: 3
            periodSeconds: 10
      volumes:
        - name: klusterlet-config
          secret:
            secretName: hub-kubeconfig
            defaultMode: 420

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-spec-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-spec-sync
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: governance-policy-spec-sync
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-spec-sync
rules:
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-spec-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-spec-sync
roleRef:
  kind: Role
  name: governance-policy-spec-sync
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-spec-sync
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - governance-policy-spec-sync
  verbs:
  - "update"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: governance-policy-spec-sync
