apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: governance-policy-spec-sync-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: governance-policy-spec-sync-leader-election
subjects:
- kind: ServiceAccount
  name: governance-policy-spec-sync
  namespace: open-cluster-management-agent-addon
